### ISSUE TITLE
关于角色部位计算

### ISSUE THREAD

**Issue by lanniai** [DevenWen/maplestory_web_phaser_ts#1]
你好，我使用了你的计算方式，为何始终会有些偏差...，你使用的数值是否有改过的

**Comment by DevenWen** [comment]
我没变更过原素材的数值。但是你要注意以下一点：
1. 确定你使用的游戏框架对于图片的渲染方式，有的是用中心点（width/2， height/2）渲染的，有的是用左上角渲染（0, 0）的。
2. 目前 mxd 的素材都是针对 左上角 渲染来确定的

**Comment by illus11ion** [comment]
能否请教下，在unity 如何用中心点（width/2, height/2）来渲染 我尝试过没找到正确的算法~，我是没有使用UI的前提下

**Comment by lanniai** [comment]
> 但你要注意以下一点：
> 
> 1. 确定你使用的游戏框架对于图片的渲染，有是用中心点（width/2, height/2）渲染的，有是用左上角渲染（0, 0）的。
> 2. 目前mxd的素材针对左上角渲染都是来确定的



> 但你要注意以下一点：
> 
> 1. 确定你使用的游戏框架对于图片的渲染，有是用中心点（width/2, height/2）渲染的，有是用左上角渲染（0, 0）的。
> 2. 目前mxd的确定对象左上角渲染都是来的

    能否请教下在unity 如何用中心点（width/2, height/2）来渲染 我尝试过没找到正确的算法~，我是没有使用UI的前提下

**Comment by DevenWen** [comment]
你可能需要反过来思考，如何使用 unity 渲染左上角的素材。我没使用过 unity 的工具，但应该转化一下不算难。
1. 首先你应该继续采用我的算法，获得粘贴点(x, y)
2. 假设素材A的 width， height 是(w, h)，那么最终的贴图位置应该是 (x + w/2 , y - h/2) = (x‘, y’)
3. 再使用 unity 将素材 A 贴在 (x‘, y’) 处

**Comment by lanniai** [comment]
> 你可能需要使用unity的工具，但我没有使用unity的工具，但我应该使用unity的工具。
> 
> 1. 首先你应该继续使用我的算法，获得贴纸点(x, y)
> 2. 假设素材A的width，height是(w, h)，那么最终的贴图位置应该是(x + w/2 , y - h/2) = (x', y')
> 3. 再使用 unity 将材料贴在 (x', y') 处

多谢
