### ISSUE TITLE
关于地图的back、obj和tile

### ISSUE THREAD

**Issue by BillDong2021** [DevenWen/maplestory_web_phaser_ts#2]
您好，我正在学习unity引擎，想用unity复刻一下冒险岛。我花了一个月的时间拼接地图，现在正在寻找人物拼接方法，有幸看到您的仓库，准备这两天仔细研究一下。
看到您的地图解析与封装中大部分还未完成，如有需要，我可以分享地图back、obj和tile的拼接方法，达到如下的效果。
![屏幕截图 2022-05-10 234444](https://user-images.githubusercontent.com/83825966/167669095-adee4cb0-068e-4ed5-964b-4691ac5b2438.png)
我是非CS专业在校生，仅有半年C#基础，unity刚学两个月，前后端知识都很匮乏，希望能得到大佬的指点。

**Comment by lanniai** [comment]
如何联系你

**Comment by lanniai** [comment]
> 您好，我正在学习unity引擎，想用unity复刻一下冒险岛。我花了一个月的时间拼接地图，现在正在寻找人物拼接方法，有幸看到您的仓库，准备这两天仔细研究一下。 看到您的地图解析与封装中大部分还未完成，如有需要，我可以分享地图back、obj和tile的拼接方法，达到如下的效果。 ![屏幕截图 2022-05-10 234444](https://user-images.githubusercontent.com/83825966/167669095-adee4cb0-068e-4ed5-964b-4691ac5b2438.png) 我是非CS专业在校生，仅有半年C#基础，unity刚学两个月，前后端知识都很匮乏，希望能得到大佬的指点。

如何联系你

**Comment by DevenWen** [comment]
> 您好，我正在学习unity引擎，想用unity复刻一下冒险岛。我花了一个月的时间拼接地图，现在正在寻找人物拼接方法，有幸看到您的仓库，准备这两天仔细研究一下。 看到您的地图解析与封装中大部分还未完成，如有需要，我可以分享地图back、obj和tile的拼接方法，达到如下的效果。 ![屏幕截图 2022-05-10 234444](https://user-images.githubusercontent.com/83825966/167669095-adee4cb0-068e-4ed5-964b-4691ac5b2438.png) 我是非CS专业在校生，仅有半年C#基础，unity刚学两个月，前后端知识都很匮乏，希望能得到大佬的指点。

谢谢，最近几个月工作比较忙，最近几天计划推进一下。我希望可以获得你的支持哦。另外我本职工作是一个后端游戏研发工程师，你有需要的话也可以联系我。你可以通过 wenkangqiang 加我的微信。期待和你一起讨论。

**Comment by DevenWen** [comment]
另外关于人物拼接部分，我这边已经大量借助 Phaser 的框架机制，特别是它的动画回调机制。我自己本身不写 Unity，但我觉得这个框架应该会支持。

你可以通过看我里面的工作日志，应该就知道我整个拼接的过程。github 在我平时工作比较忙的时候，可能会少上，通过微信你可以随时和我联系。

**Comment by DevenWen** [comment]
@BillDong2021 感谢代码上的支持和讲解。现在已经成功渲染了背景图。
